### ISSUE TITLE
Apply default CSS properties

### ISSUE THREAD

**Issue by niksy** [jonathantneal/postcss-pseudo-class-enter#2]
When you apply hover styles to your focus styles, you usually want to remove default outline applied by focus.

What do you think about providing the option of applying the removal of outline?

Something along the lines of:

``` js
{
    removeFocusOutline: true
}
```

And applied CSS would look like:

``` css
.foo:enter {
    color:red;
}
```

``` css
.foo:hover, .foo:focus {
    outline:0;
    color:red;
}
```
